# dtype, rank, shape
 
Sungchul Lee  

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

# Data types

<div align="center"><img src="img/USB-type-C.jpg" width="40%" height="10%"></div>

https://pinnacle.jobs/wp-content/uploads/2016/06/winner-1013979_1280.jpg

### .dtype 

> 데이타타입 확인

### tf.cast

> 데이타타입 변환

<div align="center"><img src="img/Data types.png" width="100%" height="10%"></div>

https://www.tensorflow.org/versions/r0.12/resources/dims_types

# .dtype

In [1]:
import tensorflow as tf

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
A = tf.constant([[2, 3, 1], [3, 1, 0]])
B = tf.constant([[2., 3., 1.], [3., 1., 0.]])
C = tf.constant([[True, True, False], [True, True, False]])

print("Data type of A:", A.dtype)
print("Data type of B:", B.dtype)
print("Data type of C:", C.dtype)

Data type of A: <dtype: 'int32'>
Data type of B: <dtype: 'float32'>
Data type of C: <dtype: 'bool'>


# tf.cast

In [3]:
u = tf.constant([2, 2, 1, 0, 7])
v = tf.constant([2, 0, 1, 0, 7])

a         = tf.equal(u, v) 
a_int32   = tf.cast(a, dtype=tf.int32)
a_int64   = tf.cast(a, dtype=tf.int64)
a_float32 = tf.cast(a, dtype=tf.float32)
a_float64 = tf.cast(a, dtype=tf.float64) 

with tf.Session() as sess:
    print("a         : ", sess.run(a)) 
    print("a_int32   : ", sess.run(a_int32)) 
    print("a_int64   : ", sess.run(a_int64)) 
    print("a_float32 : ", sess.run(a_float32))
    print("a_float64 : ", sess.run(a_float64))

a         :  [ True False  True  True  True]
a_int32   :  [1 0 1 1 1]
a_int64   :  [1 0 1 1 1]
a_float32 :  [1. 0. 1. 1. 1.]
a_float64 :  [1. 0. 1. 1. 1.]


# Rank related functions

<div align="center"><img src="img/winner-1013979_1280.jpg" width="30%" height="10%"></div>

https://pinnacle.jobs/wp-content/uploads/2016/06/winner-1013979_1280.jpg

### tf.rank, tf.reduce_sum, tf.reduce_mean


<div align="center"><img src="img/Rank.png" width="100%" height="10%"></div>

https://www.tensorflow.org/versions/r0.12/resources/dims_types

# tf.rank

In [4]:
A = tf.constant(1)
B = tf.constant([1])
C = tf.constant([[1,5,1], [3,5,1]])
D = tf.constant([[[1,5,1], [3,5,1]]])

a = tf.rank(A)
b = tf.rank(B)
c = tf.rank(C)
d = tf.rank(D)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

0
1
2
3


# tf.reduce_sum 

In [5]:
X = tf.constant([[ 2., 2., 2.], 
                 [-3., 3., 0.]])

In [6]:
a = tf.reduce_sum(X, 0)
b = tf.reduce_sum(X, 1)
c = tf.reduce_sum(X)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

[-1.  5.  2.]
[6. 0.]
6.0


# tf.reduce_mean

In [7]:
a = tf.reduce_mean(X, 0)
b = tf.reduce_mean(X, 1)
c = tf.reduce_mean(X)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

[-0.5  2.5]
[2. 0.]
1.0


# Shape related functions

<div align="center"><img src="img/24ccf3d629531aa147ded03bf3cd3e7c.png" width="30%" height="10%"></div>

https://i.pinimg.com/originals/24/cc/f3/24ccf3d629531aa147ded03bf3cd3e7c.png

### tf.shape, tf.size, tf.reshape

<div align="center"><img src="img/Shape.png" width="100%" height="10%"></div>

https://www.tensorflow.org/versions/r0.12/resources/dims_types

In [8]:
A = tf.constant(2)
B = tf.constant([2, 1])
C = tf.constant([[1,5,1],[3,5,1]])
D = tf.constant([[[1,5,1],[3,5,1]]])

# tf.shape

In [9]:
a = tf.shape(A)
b = tf.shape(B)
c = tf.shape(C)
d = tf.shape(D)
        
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

[]
[2]
[2 3]
[1 2 3]


# tf.size

In [10]:
a = tf.size(A)
b = tf.size(B)
c = tf.size(C)
d = tf.size(D)
        
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

1
2
6
6


# tf.reshape

In [9]:
a = tf.reshape(A, (1,))
b = tf.reshape(B, (1,2))
c = tf.reshape(C, (1,2,3))
d = tf.reshape(D, (2,3))
        
with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

[2]
[[2 1]]
[[[1 5 1]
  [3 5 1]]]
[[1 5 1]
 [3 5 1]]


In [12]:
A = tf.constant([1,5,1])

if 1:
    a = tf.reshape(A, (-1,1))
elif 1: 
    # TypeError: Expected binary or unicode string, got None
    a = tf.reshape(A, (None,1))
        
with tf.Session() as sess:
    print(sess.run(a))

[[1]
 [5]
 [1]]


# .dtype, tf.rank, tf.shape in action

<img src="https://www.maxim.com/.image/t_share/MTQ3NDA5NDkyOTUzMjc4MDgw/soldiers-in-combat.png" width="100%" height="10%">

In [13]:
X_ = tf.placeholder(tf.int32, (None), name="X_")    # dtype: int32, rank: 1, shape [7]

a = X_
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

int32
1
[7]
[ 2  5  1  0  9  7 10]


In [14]:
X = tf.one_hot(X_, 11)    # dtype: float32, rank: 2, shape [7 11]

a = X
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

float32
2
[ 7 11]
[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [15]:
W = tf.get_variable("W", shape=[11, 4],
                    initializer=tf.contrib.layers.xavier_initializer())    # dtype: float32, rank: 2, shape [11 4]

a = W
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

float32
2
[11  4]
[[ 0.57848054  0.1973319  -0.58582205  0.5232299 ]
 [-0.2630936  -0.08591169  0.48952824  0.30674285]
 [ 0.5977693  -0.16792393 -0.23447877 -0.37580454]
 [-0.0146656  -0.09055805  0.28681862  0.553682  ]
 [ 0.36585552 -0.33236417 -0.38106936 -0.26882342]
 [ 0.28463113  0.13292378  0.05563349 -0.583046  ]
 [ 0.15907049 -0.36832497 -0.11576492  0.59422594]
 [-0.60356283  0.3340705  -0.00199753  0.10533208]
 [ 0.5034618  -0.3074455  -0.44204065  0.11234045]
 [-0.4991908   0.15841877 -0.15557021  0.61724645]
 [-0.31964028 -0.37866637 -0.04993612 -0.2749889 ]]


In [16]:
b = tf.get_variable("b", initializer=tf.constant(0., shape=[1, 4]))    # dtype: float32, rank: 2, shape [1 4]

a = b
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

float32
2
[1 4]
[[0. 0. 0. 0.]]


In [17]:
Q = tf.matmul(X, W) + b    # dtype: float32, rank: 2, shape [7 4]

a = Q
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

float32
2
[7 4]
[[-0.03207874 -0.5188475  -0.55819154 -0.2965053 ]
 [-0.4296844   0.25036138 -0.0641697   0.2796169 ]
 [ 0.2816432   0.5013731  -0.3549314   0.2030139 ]
 [ 0.31256104  0.47784346 -0.0909242   0.2894196 ]
 [-0.03188014 -0.30414426  0.05374199 -0.28384444]
 [-0.4345799  -0.6157152   0.15666509  0.1941778 ]
 [ 0.22736424 -0.2007299   0.35025996  0.60422915]]


In [18]:
greedy_action = tf.argmax(Q, axis=1)    # dtype: int64, rank: 1, shape [7]

a = greedy_action
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

int64
1
[7]
[0 1 3 2 2 3 1]


In [19]:
Greedy_action = greedy_action[0]    # type: int64, rank: 0, shape []

a = Greedy_action
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], feed_dict={X_: [2,5,1,0,9,7,10]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

int64
0
[]
2


In [ ]:
ACTIONS_ = tf.placeholder(tf.int32, [None], name="ACTIONS_")    # dtype: int32, rank: 1, shape [7]

a = ACTIONS_
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
ACTIONS = tf.one_hot(ACTIONS_, 4, 
                     on_value = True, off_value = False, 
                     dtype = tf.bool)    # dtype: bool,  rank: 2, shape [7 4]

a = ACTIONS
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
q_now = tf.boolean_mask(Q, ACTIONS)    # dtype: float32, rank: 1, shape [7]

a = q_now
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
Q_now = tf.reshape(q_now, shape=[-1, 1])    # dtype: float32, rank: 2, shape [7 1]

a = Q_now
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
Q_max = tf.reduce_max(Q, axis=1, keep_dims=True)    # dtype: float32, rank: 2, shape [7 1]

a = Q_max
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
DONES_ = tf.placeholder(tf.int32, [None], name="DONES_")    # dtype: int32, rank: 1, shape [7]

a = DONES_
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
dones = tf.reshape(DONES_, [-1, 1])    # dtype: int32, rank: 2, shape [7 1]

a = dones
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
DONES = tf.cast(dones, tf.float32)    # dtype: float32, rank: 2, shape [7 1]

a = DONES
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
REWARDS_ = tf.placeholder(tf.float32, [None], name="REWARDS_")    # dtype: float32, rank: 1, shape [7]

a = REWARDS_
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1],
                                                         REWARDS_: [-0.02,-0.02,0.98,-0.02,-0.02,-0.02,-1.02]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
REWARDS = tf.reshape(REWARDS_, [-1, 1])    # dtype: float32, rank: 2, shape [7 1]   

a = REWARDS
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1],
                                                         REWARDS_: [-0.02,-0.02,0.98,-0.02,-0.02,-0.02,-1.02]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
# DONES -    dtype: float32, rank: 2, shape [7 1]
# REWARDS -  dtype: float32, rank: 2, shape [7 1]
# Q_max -    dtype: float32, rank: 2, shape [7 1]
gamma = 0.99
Q_target = (1 - DONES) * (REWARDS + gamma * Q_max) + DONES * REWARDS    # dtype: float32, rank: 2, shape [7 1]

a = Q_target
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1],
                                                         REWARDS_: [-0.02,-0.02,0.98,-0.02,-0.02,-0.02,-1.02]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)

In [ ]:
loss = tf.reduce_mean(tf.square(Q_target-Q_now))    # dtype: float32, rank: 0, shape []

a = loss
a_rank = tf.rank(a)
a_shape = tf.shape(a)

with tf.Session() as sess:
    tf.global_variables_initializer().run()

    a_run, a_rank_run, a_shape_run = sess.run([a, a_rank, a_shape], 
                                              feed_dict={X_: [2,5,1,0,9,7,10],
                                                         ACTIONS_: [2,0,1,0,3,2,1],
                                                         DONES_: [0,0,1,0,0,0,1],
                                                         REWARDS_: [-0.02,-0.02,0.98,-0.02,-0.02,-0.02,-1.02]})
    print(a_run.dtype)
    print(a_rank_run)
    print(a_shape_run)
    print(a_run)