# Component-wise operations
 
Sungchul Lee  

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

### tf.add (or +), tf.subtract (or -), tf.multiply (or *), tf.div (or /)

### tf.mod (or %)

### tf.square, tf.sqrt, and tf.pow

### tf.sin, tf.cos, and tf.tan

### tf.abs

### tf.round, tf.ceil, and tf.floor

- Works for same shape matrices 

- Works even for different shape matrices if 브로드게스팅이 가능하면

- Works even for different rank matrices if 브로드게스팅이 가능하면 

- <font  style="color:red">WARNING: Should be same date type</font> 

# tf.add (or +), tf.subtract (or -), tf.multiply (or *), tf.div (or /)

In [1]:
import tensorflow as tf

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
X = tf.constant([[2, 3], 
                 [3, 1]])
if 1: 
    # Works for same shape matrices
    Y = tf.constant([[1, 0], 
                     [0, 1]])
elif 1: 
    # TypeError: 
    # Input 'y' of 'Add' Op has type float32 that does not match 
    # type int32 of argument 'x'.
    Y = tf.constant([[1., 0.], 
                     [0., 1.]])
elif 0: 
    # Works for different shape matrices if 브로드게스팅이 가능하면  
    Y = tf.constant([[1], 
                     [0]])
elif 0: 
    # Works for different shape matrices if 브로드게스팅이 가능하면 
    Y = tf.constant([[1, 0]])
elif 0: 
    # Works for different rank matrices if 브로드게스팅이 가능하면 
    Y = tf.constant([1])    
elif 0: 
    # Works for different rank matrices if 브로드게스팅이 가능하면 
    Y = tf.constant(1)

if 1: 
    a, b = tf.add(X, Y), X + Y
elif 0: 
    a, b = tf.subtract(X, Y), X - Y
elif 0: 
    a, b = tf.multiply(X, Y), X * Y
elif 0: 
    a, b = tf.div(X, Y), X / Y

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[3 3]
 [3 2]]
[[3 3]
 [3 2]]


# tf.mod (or %)

In [3]:
X = tf.constant([[1.,  2.], [3., 4.]])
Y = tf.constant([[2., -4.], [2., 3.]])

In [4]:
a = tf.mod(X, 2)
b = X % 2

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[1. 0.]
 [1. 0.]]
[[1. 0.]
 [1. 0.]]


# tf.square, tf.sqrt, and tf.pow

In [5]:
a = tf.square(X)
b = tf.pow(X, 2)
c = tf.pow(X, 3)
d = tf.pow(X, Y)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  4.]
 [ 9. 16.]]
[[ 1.  8.]
 [27. 64.]]
[[1.00e+00 6.25e-02]
 [9.00e+00 6.40e+01]]


# tf.sin, tf.cos, and tf.tan

In [6]:
a = tf.sin(X)
b = tf.cos(X)
c = tf.tan(X)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

[[ 0.84147096  0.9092974 ]
 [ 0.14112    -0.7568025 ]]
[[ 0.5403023  -0.41614684]
 [-0.9899925  -0.6536436 ]]
[[ 1.5574077  -2.1850398 ]
 [-0.14254655  1.1578213 ]]


# tf.abs

In [7]:
a = tf.abs(X)

with tf.Session() as sess:
    print(sess.run(a))

[[1. 2.]
 [3. 4.]]


# tf.round, tf.ceil, and tf.floor

In [8]:
a = tf.round(X)
b = tf.ceil(X)
c = tf.floor(X)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
[[1. 2.]
 [3. 4.]]
