# tf.one_hot
 
Sungchul Lee  

<div align="center"><img src="img/2017-02-04-char-rnn-onehot.png" width="100%" height="10%"></div>

https://hjweide.github.io/char-rnn

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

```
tf.one_hot(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    ype=None,
    name=None
)
```

dthttps://www.tensorflow.org/versions/r1.8/api_docs/python/tf/one_hot

In [1]:
import tensorflow as tf

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.one_hot([0, 1, 2, 1], 5)
b = tf.one_hot([0, 1, 2, 1], 7)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]]


In [3]:
a = tf.one_hot([0, 1, 2, 1], 5)
a_boolean = tf.one_hot([0, 1, 2, 1], 5, on_value = True, off_value = False, dtype = tf.bool)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(a_boolean))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0.]]
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False  True False False False]]
