# tf.argmax and tf.reduce_max
 
Sungchul Lee  

<div align="center"><img src="img/75341fb373e410eb339784e65a09f140.jpg" width="30%"></div>

http://static.metacritic.com/images/products/movies/1/75341fb373e410eb339784e65a09f140.jpg

# How to run these slides yourself

**Setup python environment**

- [Install RISE for an interactive presentation viewer](https://github.com/damianavila/RISE)

In [1]:
# tf.argmax (tf.argmin)

> For each row, find argmax.

> The rank is down by 1.

```
tf.argmax(
    input,
    axis=None,
    name=None,
    dimension=None,
    output_type=tf.int64
)
```

https://www.tensorflow.org/api_docs/python/tf/argmax

In [2]:
import tensorflow as tf

/Users/sungchul/anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)
/Users/sungchul/anaconda/lib/python3.5/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
t = tf.constant([[1, 8, 3], 
                 [4, 7, 6], 
                 [9, 2, 5]])

In [4]:
if 0:
    # 각각의 칼럼에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t) 
elif 0:
    # 각각의 칼럼에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t, axis=0)
elif 1:
    # 각각의 로에서 최대값이 발생하는 인덱스를 찿음
    argmax_where = tf.argmax(t, axis=1)

with tf.Session() as sess:
    print(sess.run(argmax_where))

[1 1 0]


# tf.reduce_max (tf.reduce_min)

> For each row, find max

> The rank is down by 1. 

> You can use 'keepdims=True' to keep the current rank.

```
tf.reduce_max(
    input_tensor,
    axis=None,
    keepdims=None,
    name=None,
    reduction_indices=None
)
```

https://www.tensorflow.org/versions/r1.8/api_docs/python/tf/reduce_max

In [5]:
if 0:
    # 최대값 찿음
    M = tf.reduce_max(t) 
elif 1:
    # 각각의 칼럼에서 최대값 찿음
    M = tf.reduce_max(t, axis=0)
elif 1:
    # 각각의 로에서 최대값 찿음
    M = tf.reduce_max(t, axis=1)

with tf.Session() as sess:
    print(sess.run(M))

[9 8 6]


# keepdims=True

In [6]:
if 0:
    # 최대값 찿음
    M = tf.reduce_max(t, keepdims=True) 
elif 0:
    # 각각의 칼럼에서 최대값 찿음
    M = tf.reduce_max(t, axis=0, keepdims=True)
elif 1:
    # 각각의 로에서 최대값 찿음
    M = tf.reduce_max(t, axis=1, keepdims=True)

with tf.Session() as sess:
    print(sess.run(M))

[[8]
 [7]
 [9]]
