In [ ]:
print("tf.concat")

import tensorflow as tf

c1 = tf.constant([1, 3, 5, 7, 9, 0, 2, 4, 6, 8])
c2 = tf.constant([1, 3, 5])

v1 = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2]])
v2 = tf.constant([[1, 2, 3], [7, 8, 9]])

a = tf.concat(0, [c1, c2])
b = tf.concat(1, [v1, v2])

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

In [ ]:
print("tf.gather")

import tensorflow as tf

u = tf.constant([1, 3, 5, 7, 9, 0, 2, 4, 6, 8])
v = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2]])

a = tf.gather(u, [2, 5, 2, 5]) # [2nd item, 5th item, 2nd item, 5th item]
b = tf.gather(v, [1, 0]) # [1st item, 0th item]
c = tf.gather(v, [[0, 0], [1, 1]]) # [[0th item, 0th item], [1st item, 1st item]]

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

In [ ]:
print("tf.maximum and tf.minimum")

import tensorflow as tf

X = tf.constant([[2., 2.], [-3., 3.]])
Y = tf.constant([[2., -4.], [2., 3.]])

a = tf.maximum(X, Y)
b = tf.minimum(X, Y)

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

In [6]:
print("tf.nn.in_top_k")

import tensorflow as tf

logit = tf.constant([[1.0, 0.7, 2.0, 0.5, 2.7, -6.3]])
label = tf.constant([[  0,   0,   1,   0,   0,    0]])
label_argmax = tf.argmax(label, 1)
a = tf.nn.in_top_k(logit, label_argmax, 1)  # [False]
b = tf.nn.in_top_k(logit, label_argmax, 2)  # [ True]
c = tf.nn.in_top_k(logit, label_argmax, 3)  # [ True]

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

tf.nn.in_top_k
[False]
[ True]
[ True]


In [7]:
print("tf.nn.max_pool") 

import tensorflow as tf

x = tf.constant([[[[1., 2., 3., 4.],
                 [2., 3., 4., 5.]]]])
a = tf.nn.max_pool(x, ksize=[1, 2, 2, 1], strides=[1, 2, 2, 1], padding='SAME')

with tf.Session() as sess:
    print(sess.run(a))

tf.nn.max_pool
[[[[ 2.  3.  4.  5.]]]]


In [10]:
print("tf.nn.softmax")

import tensorflow as tf

A = tf.constant([[2., 1.]])
a = tf.nn.softmax(A)
a1 = tf.exp(A) / tf.reduce_sum(tf.exp(A))

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(a1))

tf.nn.softmax
[[ 0.7310586   0.26894143]]
[[ 0.7310586  0.2689414]]


In [14]:
print("tf.pad")

import tensorflow as tf

v = tf.constant([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])
# tf.pad(input, [[top_pad_size, down_pad_size], [left_pad_size, right_pad_size]], pad_mathod)
a = tf.pad(v, [[1, 2], [3, 4]], 'CONSTANT')
b = tf.pad(v, [[1, 2], [3, 4]], 'REFLECT')
c = tf.pad(v, [[1, 2], [3, 4]], 'SYMMETRIC')

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

tf.pad
[[0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 2 3 4 5 0 0 0 0]
 [0 0 0 1 2 3 4 5 0 0 0 0]
 [0 0 0 1 2 3 4 5 0 0 0 0]
 [0 0 0 1 2 3 4 5 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0]]
[[4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]
 [4 3 2 1 2 3 4 5 4 3 2 1]]
[[3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]
 [3 2 1 1 2 3 4 5 5 4 3 2]]


In [ ]:
print("tf.reverse")  

import tensorflow as tf

u = tf.constant([1, 2, 3, 4, 5, 6])
v = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2]])

a = tf.reverse(u, [True])
b = tf.reverse(v, [True, False])
c = tf.reverse(v, [True, True])

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))

In [3]:
print("tf.sign") 

import tensorflow as tf

X = tf.constant([[2, 2.], [-3, 0]])

a = tf.sign(X)

with tf.Session() as sess:
    print(sess.run(a))

tf.sign
[[ 1.  1.]
 [-1.  0.]]


In [ ]:
print("tf.slice")  

import tensorflow as tf

u = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
v = tf.constant([[1, 2, 3, 4, 5, 6], [7, 8, 9, 0, 1, 2]])

# tf.slice(input, begin_spot, size_to_slice)
a = tf.slice(u, [2], [3])
b = tf.slice(v, [0, 2], [1, 2])
c = tf.slice(v, [0, 2], [2, 2])
d = tf.slice(v, [0, 2], [2,-1])

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))

In [ ]:
print("tf.split")   

import tensorflow as tf

A = tf.random_normal([5, 30])

# tf.slice(axis_to_split, numbers_of_pieces_after_splitting, input)
split_0, split_1, split_2, split_3, split_4, split_5 = tf.split(1, 6, A)
SPLIT_0, SPLIT_1, SPLIT_2 = tf.split(1, 3, A)

with tf.Session() as sess:
    print(sess.run( tf.shape(split_0) ))
    print(sess.run( tf.shape(split_1) ))
    print(sess.run( tf.shape(split_2) ))
    print(sess.run( tf.shape(SPLIT_0) ))
    print(sess.run( tf.shape(SPLIT_1) ))
    print(sess.run( tf.shape(SPLIT_2) ))

In [ ]:
print("tf.squeeze")  

import tensorflow as tf

A = tf.constant([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

# Removes dimensions of size 1 from the shape of a tensor.
# Given a tensor input, this operation returns a tensor of the same type with all dimensions of size 1 removed.
# If you don't want to remove all size 1 dimensions, you can remove specific size 1 dimensions by specifying squeeze_dims.
a = tf.reshape(A, [4, 1, 3])
b = tf.squeeze(a)

with tf.Session() as sess:
    print(sess.run( tf.shape(a) ))
    print(sess.run( tf.shape(b) ))

In [ ]:
print("tf.tile")

import tensorflow as tf

u = tf.constant([1, 3, 5])
v = tf.constant([[1, 2, 3], [7, 8, 9]])

a = tf.tile(u, [3])
b = tf.tile(v, [2, 2])

with tf.Session() as sess:
    print(sess.run( tf.shape(a) ))
    print(sess.run( tf.shape(b) ))

In [ ]:
print("tf.to_int64")

import tensorflow as tf

a = tf.to_int64(3.14)
b = tf.to_int64([0.7, 0.3, -1.5, -10.5, 3.14])

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(b))

In [ ]:
print("tf.unstack")

import numpy as np, tensorflow as tf

num_classes = 5
size = 50
x = np.array(np.random.choice(num_classes, size=(size,)))

batch_size = 5
num_steps = 10
data_x = np.zeros([batch_size, num_steps], dtype=np.int32)
for i in range(batch_size):
    data_x[i] = x[num_steps * i:num_steps * (i + 1)]

x_one_hot = tf.one_hot(data_x, num_classes)
rnn_inputs = tf.unstack(x_one_hot, axis=1)

with tf.Session() as sess:
    print(data_x)
    print(sess.run(x_one_hot))
    print(sess.run(rnn_inputs))