# Save And Load Trained Model

Machine Learning With Python - 5: Save Model Using Joblib And Pickle by codebasics [youtube](https://www.youtube.com/watch?v=KfnhNlD8WZI) [github](https://github.com/codebasics/py/tree/master/ML/4_save_model)

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv("data/homeprices.csv")
df.head()

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [3]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [4]:
model.coef_

array([135.78767123])

In [5]:
model.intercept_

180616.43835616432

In [6]:
model.predict(5000)

array([859554.79452055])

# Save Model To a File Using Python Pickle

In [7]:
import pickle

In [8]:
with open('data/model_pickle','wb') as file:
    pickle.dump(model,file)

# Load Saved Model

In [9]:
with open('data/model_pickle','rb') as file:
    mp = pickle.load(file)

In [10]:
mp.coef_

array([135.78767123])

In [11]:
mp.intercept_

180616.43835616432

In [12]:
mp.predict(5000)

array([859554.79452055])

# Save Trained Model Using joblib

In [13]:
from sklearn.externals import joblib

In [14]:
joblib.dump(model, 'data/model_joblib')

['data/model_joblib']

# Load Saved Model

In [15]:
mj = joblib.load('data/model_joblib')

In [16]:
mj.coef_

array([135.78767123])

In [17]:
mj.intercept_

180616.43835616432

In [18]:
mj.predict(5000)

array([859554.79452055])