# Introduction

[numpy tutorial - Introduction by codebasics](https://www.youtube.com/watch?v=rN0TREj8G7U)

# numpy 설치방법

> $ pip install numpy

> $ pip install numpy --upgrade 

> install anaconda

# Dependencies

<div align="center"><img src="img/Screen Shot 2018-08-08 at 3.55.26 PM.png" width="70%"></div>

Python: Pandas Tutorial | Intro to DataFrames by Joe James 
[youtube](https://www.youtube.com/watch?v=e60ItwlZTKM&t=18s) 
[github](https://github.com/joeyajames/Python)

# numpy 임포트 방법

In [1]:
import numpy as np

In [2]:
import sys
import time

# np.ndarray 만드는 방법

In [3]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a = np.arange(1,12,2)
a

array([ 1,  3,  5,  7,  9, 11])

In [5]:
a = np.linspace(1,12,6)
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [6]:
a = np.linspace(1,12,6).reshape(3,2)
a

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [7]:
a = np.array([[-1., -0.6, -0.2],
              [0.2, 0.6, 1.]])
a

array([[-1. , -0.6, -0.2],
       [ 0.2,  0.6,  1. ]])

In [8]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
a = np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
a = np.empty((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
a = np.random.uniform(0.,1.,(2,3))
u = np.zeros_like(a)
u

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
a = np.random.uniform(0.,1.,(2,3))
u = np.ones_like(a)
u

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
a = np.random.uniform(0.,1.,(2,3))
u = np.empty_like(a)
u

array([[0.17218296, 0.28713261, 0.39003205],
       [0.49109421, 0.02756574, 0.12640033]])

In [14]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [15]:
a = np.eye(2,3)
a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [16]:
a = np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [17]:
a = np.full((2, 2), 7.)
a

array([[7., 7.],
       [7., 7.]])

In [18]:
a = np.random.uniform(0.,1.,(3,4))
a

array([[0.29105069, 0.69729838, 0.32546765, 0.9286783 ],
       [0.52521193, 0.82158304, 0.52067893, 0.82764388],
       [0.18417217, 0.68368388, 0.46505496, 0.11014617]])

In [19]:
a = np.random.normal(0.,1.,(3,4))
a

array([[ 0.57615235,  0.19856991, -0.00896286,  0.82419877],
       [-0.90886833, -1.31336942,  2.12992925,  2.09687285],
       [ 0.92019612, -0.48709015,  0.25730328, -0.27564818]])

In [20]:
for i in range(10):
    print(np.random.randint(5,10,2), end=', ')

[5 8], [7 5], [5 7], [5 6], [6 7], [9 5], [6 9], [5 7], [6 9], [5 8], 

In [21]:
a = np.arange(10)
np.random.shuffle(a) # inplace function
a

array([4, 3, 1, 9, 0, 8, 7, 2, 6, 5])

In [22]:
a = np.arange(10)
np.random.shuffle(a) # inplace function
a.sort() # inplace function
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
a = np.arange(10)
for i in range(50):
    print(np.random.choice(a), end=', ')

6, 6, 2, 8, 9, 3, 4, 2, 4, 9, 5, 9, 4, 4, 0, 5, 0, 1, 5, 1, 5, 6, 0, 2, 4, 7, 1, 3, 6, 5, 8, 5, 4, 8, 7, 7, 9, 1, 3, 2, 2, 6, 4, 6, 6, 6, 2, 8, 5, 6, 

# np.set_printoptions

np.set_printoptions을 이용, 프린트할 때 여러가지 옵션을 조정할 수 있다.
precision=2이면 소수점이하 2자리까지만 프린트하라는 것이고,
suppress=True이면 사이언티픽 노테이션 사용하지 말라는 이야기이다.

In [24]:
np.set_printoptions(precision=2, suppress=True)

In [25]:
a = np.random.normal(0.,1.,(3,4))
a

array([[-1.68, -0.43,  0.03, -0.84],
       [-0.3 , -0.3 , -1.14, -0.61],
       [-1.95,  0.01, -0.11, -1.19]])

In [26]:
a[0,0]

-1.68489780999706

# np.ndarray는 list와 매우 비슷하다

In [27]:
a[0]

array([-1.68, -0.43,  0.03, -0.84])

In [28]:
a[1]

array([-0.3 , -0.3 , -1.14, -0.61])

In [29]:
a[3:7]

array([], shape=(0, 4), dtype=float64)

# Why do I need np.ndarray

<div align="center"><img src="img/Screen Shot 2018-08-05 at 1.39.43 PM.png" width="70%"></div>

[Python: NumPy | Numerical Python Arrays Tutorial by Joe James](https://www.youtube.com/watch?v=8Mpc9ukltVA&t=316s)

<div align="center"><img src="img/Screen Shot 2018-08-05 at 1.52.39 PM.png" width="70%"></div>

[Python: NumPy | Numerical Python Arrays Tutorial by Joe James](https://www.youtube.com/watch?v=8Mpc9ukltVA&t=316s)

# 타이핑을 적게한다

In [30]:
a = np.array([1,2,3])
b = np.array([4,5,6])

이 두 리스트에 있는 숫자들을 component-wise addition을 하여보자.

In [31]:
# numpy implementaion
c = a + b
c

array([5, 7, 9])

In [32]:
# python list implementaion
c = []
for i in range(len(a)):
    c.append(a[i]+b[i])
c

[5, 7, 9]

In [33]:
# python list comprehension implementaion
c = [x + y for x, y in zip(a,b)]
c

[5, 7, 9]

# 계산속도가 빠르다

1부터 n까지의 정수를 더하는 작업을 생각하자.

In [34]:
n = int(1e+8)
list_n = [i for i in range(n)]
np_array_n = np.arange(n)

쥬피터 노트북의 매직함수 %timeit를 써서 시간을 재 보자. 

In [35]:
%timeit sum(list_n)

1 loop, best of 3: 787 ms per loop


In [36]:
%timeit np.sum(np_array_n)

10 loops, best of 3: 59 ms per loop


time 모듈을 써서 시간을 재 보자. 

In [37]:
t0 = time.time()
sum(list_n)
t1 = time.time()
print('python list took {} ms'.format((t1-t0)*1000))

python list took 890.4800415039062 ms


In [38]:
t0 = time.time()
np.sum(np_array_n)
t1 = time.time()
print('np.ndarray took {} ms'.format((t1-t0)*1000))

np.ndarray took 58.92801284790039 ms


쥬피터 노트북의 매직함수 %timeit를 써서 시간을 재면, 여러 번 실행해서 평균적인 트랜드를 확인한다.
time 모듈을 써서 시간을 재면, 한 번 실행해서 시간을 잰다.
쥬피터 노트북의 매직함수 %timeit가 좀 더 정확한 컴퓨팅 시간에 관한 정보를 제공하지만, 
이 기능은 쥬피터 노트북에서만 가능하다.

# 메모리를 적게 사용한다

memory_profiler를 pip을 이용 설치하자.

> $ pip install memory_profiler

memory_profiler를 로드하자.

In [39]:
%load_ext memory_profiler

memory_profiler의 매직함수 %memit으로 사용 메모리를 측정하여 보자. 

In [40]:
%memit [i for i in range(n)]

peak memory: 7894.81 MiB, increment: 3217.42 MiB


In [41]:
%memit np.arange(n)

peak memory: 5408.86 MiB, increment: 725.20 MiB


Peak memory refers to the peak memory usage of your system (including memory usage of other processes) during the program runtime.

Increment is the increment in memory usage relative to the memory usage just before the program is run (i.e. increment = peak memory - starting memory).

So you'd report increment. Peak memory just helps you figure how close you are to using all your RAM during a program run.

https://stackoverflow.com/questions/45318536/trying-to-understand-python-memory-profiler

list는 여러가지 다양한 형태의 데이타를 담을 수 있지만,
np.ndarray는 한 종류의 데이타 만을 담을 수 있다.
list는 여러가지 다양한 형태의 데이타를 담기 때문에 
각각의 데이타를 담을 때 추가적으로 이 데이타가 어떤 형태의 데이타인지를 설명하는 메타 데이타가 들어간다.
이와는 대조적으로
np.ndarray는 한 종류의 데이타 만을 담기 때문에
각각의 데이타에 메타 데이타가 들어가는 것이 아니고
통으로 하나의 메타 데이타가 들어간다.
이것이 np.ndarray가 list에 비하여 메모리를 적게 사용하는 이유다.

In [42]:
temp_1 = [i for i in range(n)]
temp_2 = np.arange(n)

m1 = sys.getsizeof(5) 
m2 = temp_2.itemsize 
print("Essential Memory Usage of one item in list       : {:>10} Bytes".format(m1))
print("Essential Memory Usage of one item in np.ndarray : {:>10} Bytes".format(m2))

m3 = sys.getsizeof(5) * len(temp_1)
m4 = temp_2.itemsize  * temp_2.size
print("Essential Memory Usage of list       : {:>10} Bytes".format(m3))
print("Essential Memory Usage of np.ndarray : {:>10} Bytes".format(m4))

Essential Memory Usage of one item in list       :         28 Bytes
Essential Memory Usage of one item in np.ndarray :          8 Bytes
Essential Memory Usage of list       : 2800000000 Bytes
Essential Memory Usage of np.ndarray :  800000000 Bytes


<div align="center"><img src="img/Screen Shot 2018-08-19 at 6.39.27 AM.png" width="70%"></div>