# Basic Array Operations

[numpy tutorial - basic array operations by codebasics](https://www.youtube.com/watch?v=a8aDcLk4vRc)

# Important Attributes of np.ndarray

NumPy’s array class is called ndarray. It is also known by the alias array. Note that numpy.array is not the same as the Standard Python Library class array.array, which only handles one-dimensional arrays and offers less functionality. The more important attributes of an ndarray object are:

- ndarray.dtype

- ndarray.shape

- ndarray.size

- ndarray.ndim

- ndarray.itemsize

- ndarray.data

https://docs.scipy.org/doc/numpy/user/quickstart.html

<div align="center"><img src="img/Variable.png" width="50%"></div>

http://corochann.com/chainer-basic-module-introduction-1098.html

# dtype

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 

### list

- Each may have different data type

### np.ndarray

- All have same data type

- Fast

In [1]:
import numpy as np

In [2]:
def print_info(u):
    try:
        print(u)
        print("type:     ", type(u))
        print("len:      ", len(u))
        print("dtype:    ", u.dtype)
        print("shape:    ", u.shape)    
        print("size:     ", u.size)
        print("ndim:     ", u.ndim)
        print("itemsize: ", u.itemsize)
        print("data:     ", u.data)
        print("np.linalg.matrix_rank: ", np.linalg.matrix_rank(u))
    except Exception as e:
        print(e)

In [3]:
u = [1, 2, 3, 4]     
print_info(u)

[1, 2, 3, 4]
type:      <class 'list'>
len:       4
'list' object has no attribute 'dtype'


In [4]:
if 1:
    u = np.array([1, 2, 3, 4]) 
elif 1:
    u = np.array((1, 2, 3, 4)) 
print_info(u)

[1 2 3 4]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     int64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x10624c288>
np.linalg.matrix_rank:  1


In [5]:
u[0]

1

In [6]:
u[1]

2

In [7]:
a = np.arange(10) 
print_info(a)

[0 1 2 3 4 5 6 7 8 9]
type:      <class 'numpy.ndarray'>
len:       10
dtype:     int64
shape:     (10,)
size:      10
ndim:      1
itemsize:  8
data:      <memory at 0x1058e0948>
np.linalg.matrix_rank:  1


In [8]:
a = np.arange(0,10) 
print_info(a)

[0 1 2 3 4 5 6 7 8 9]
type:      <class 'numpy.ndarray'>
len:       10
dtype:     int64
shape:     (10,)
size:      10
ndim:      1
itemsize:  8
data:      <memory at 0x10624c288>
np.linalg.matrix_rank:  1


In [9]:
a = np.arange(0,10,2) 
print_info(a)

[0 2 4 6 8]
type:      <class 'numpy.ndarray'>
len:       5
dtype:     int64
shape:     (5,)
size:      5
ndim:      1
itemsize:  8
data:      <memory at 0x10624c288>
np.linalg.matrix_rank:  1


In [10]:
u = np.linspace(0, 10)     
print_info(u)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
type:      <class 'numpy.ndarray'>
len:       50
dtype:     float64
shape:     (50,)
size:      50
ndim:      1
itemsize:  8
data:      <memory at 0x10624c288>
np.linalg.matrix_rank:  1


In [11]:
u = np.linspace(0, 10, 10)     
print_info(u)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
type:      <class 'numpy.ndarray'>
len:       10
dtype:     float64
shape:     (10,)
size:      10
ndim:      1
itemsize:  8
data:      <memory at 0x10624c348>
np.linalg.matrix_rank:  1


In [12]:
if 1:
    a = np.array([[-1., -0.6, -0.2], 
                  [0.2, 0.6, 1.]])
elif 1:
    a = np.array([[-1., -0.6, -0.2], [0.2, 0.6, 1.]])
elif 1:
    a = np.array([(-1., -0.6, -0.2), 
                  (0.2, 0.6, 1.)])
elif 1:
    a = np.array([(-1., -0.6, -0.2), (0.2, 0.6, 1.)])
print_info(a)

[[-1.  -0.6 -0.2]
 [ 0.2  0.6  1. ]]
type:      <class 'numpy.ndarray'>
len:       2
dtype:     float64
shape:     (2, 3)
size:      6
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2


np.array를 이용할 때, 다음과 같은 실수가 많다.

In [13]:
try:
    a = np.array(-1., -0.6, -0.2)
except Exception as e:
    print(e)

only 2 non-keyword arguments accepted


# Change dtype using dtype keyword

In [14]:
u = np.array([1, 2, 3, 4])

if 1:
    v = np.array([1, 2, 3, 4], dtype=np.float64)
elif 1:
    v = np.array([1, 2, 3, 4], dtype=float)
elif 1:
    v = np.array([1, 2, 3, 4], dtype='float')
elif 1:
    v = np.array([1, 2, 3, 4], dtype='f')
    
print_info(u)
print_info(v)

[1 2 3 4]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     int64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x1058e0948>
np.linalg.matrix_rank:  1
[1. 2. 3. 4.]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     float64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x1058e0948>
np.linalg.matrix_rank:  1


In [15]:
u = np.linspace(0, 10)

if 1:
    v = np.linspace(0, 10, dtype=np.int64)
elif 1:
    v = np.linspace(0, 10, dtype=int) 
elif 1:
    v = np.linspace(0, 10, dtype='int') 
elif 1:
    v = np.linspace(0, 10, dtype='i')
    
print_info(u)
print_info(v)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
type:      <class 'numpy.ndarray'>
len:       50
dtype:     float64
shape:     (50,)
size:      50
ndim:      1
itemsize:  8
data:      <memory at 0x10624c348>
np.linalg.matrix_rank:  1
[ 0  0  0  0  0  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4
  4  5  5  5  5  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9
  9 10]
type:      <class 'numpy.ndarray'>
len:       50
d

In [16]:
a = np.array([5.,6.,7.])
a

array([5., 6., 7.])

In [17]:
a.dtype

dtype('float64')

In [18]:
a.itemsize

8

In [19]:
a = np.array([5.,6.,7.], dtype=int)
a

array([5, 6, 7])

In [20]:
a.dtype

dtype('int64')

In [21]:
a.itemsize

8

In [22]:
a = np.array([5.,6.,7.], dtype=np.float32)
a

array([5., 6., 7.], dtype=float32)

In [23]:
a.dtype

dtype('float32')

In [24]:
a.itemsize

4

In [25]:
a = np.array([5.,6.,7.], dtype=np.float16)
a

array([5., 6., 7.], dtype=float16)

In [26]:
a.dtype

dtype('float16')

In [27]:
a.itemsize

2

In [28]:
a = np.array([5.,6.,7.], dtype='complex')
a

array([5.+0.j, 6.+0.j, 7.+0.j])

In [29]:
a.dtype

dtype('complex128')

In [30]:
a.itemsize

16

In [31]:
a = np.array([5.,6.,7.])
a = np.array(a, dtype=np.float16)
a

array([5., 6., 7.], dtype=float16)

In [32]:
a.dtype

dtype('float16')

In [33]:
a.itemsize

2

# Change dtype using astype method

In [34]:
u = np.array([1, 2, 3, 4])
v = u.astype(float)
print_info(u)
print_info(v)

[1 2 3 4]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     int64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1
[1. 2. 3. 4.]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     float64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1


In [35]:
u = np.linspace(0, 10, dtype=np.float64) 
v = u.astype(int)
print_info(u)
print_info(v)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
type:      <class 'numpy.ndarray'>
len:       50
dtype:     float64
shape:     (50,)
size:      50
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1
[ 0  0  0  0  0  1  1  1  1  1  2  2  2  2  2  3  3  3  3  3  4  4  4  4
  4  5  5  5  5  5  6  6  6  6  6  7  7  7  7  7  8  8  8  8  8  9  9  9
  9 10]
type:      <class 'numpy.ndarray'>
len:       50
d

# shape

<div align="center"><img src="img/elsp_0105.png" width="50%"></div>

https://www.safaribooksonline.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png

In [36]:
a = np.linspace(1,12,6).reshape(3,2)
a

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [37]:
a.shape

(3, 2)

In [38]:
a.size

6

In [39]:
a.dtype

dtype('float64')

In [40]:
a.itemsize

8

# Change shape using reshape method

In [41]:
u = np.array([[1, 2], [3, 4], [5, 6]])
v = u.reshape((2,3))
print_info(u)
print_info(v)

[[1 2]
 [3 4]
 [5 6]]
type:      <class 'numpy.ndarray'>
len:       3
dtype:     int64
shape:     (3, 2)
size:      6
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2
[[1 2 3]
 [4 5 6]]
type:      <class 'numpy.ndarray'>
len:       2
dtype:     int64
shape:     (2, 3)
size:      6
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2


In [42]:
u = np.array([[1, 2], [3, 4]])
v = u.reshape((4,))
print_info(u)
print_info(v)

[[1 2]
 [3 4]]
type:      <class 'numpy.ndarray'>
len:       2
dtype:     int64
shape:     (2, 2)
size:      4
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2
[1 2 3 4]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     int64
shape:     (4,)
size:      4
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1


In [43]:
u = np.array([[1, 2], [3, 4]])
v = u.reshape((4,1))
print_info(u)
print_info(v)

[[1 2]
 [3 4]]
type:      <class 'numpy.ndarray'>
len:       2
dtype:     int64
shape:     (2, 2)
size:      4
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2
[[1]
 [2]
 [3]
 [4]]
type:      <class 'numpy.ndarray'>
len:       4
dtype:     int64
shape:     (4, 1)
size:      4
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  1


In [44]:
u = np.array([[[1, 2], [3, 4]]])
v = u.reshape((2,2))
print_info(u)
print_info(v)

[[[1 2]
  [3 4]]]
type:      <class 'numpy.ndarray'>
len:       1
dtype:     int64
shape:     (1, 2, 2)
size:      4
ndim:      3
itemsize:  8
data:      <memory at 0x1058fb9a8>
np.linalg.matrix_rank:  [2]
[[1 2]
 [3 4]]
type:      <class 'numpy.ndarray'>
len:       2
dtype:     int64
shape:     (2, 2)
size:      4
ndim:      2
itemsize:  8
data:      <memory at 0x1060a9c18>
np.linalg.matrix_rank:  2


In [45]:
u = np.linspace(0, 10) 
v = u.reshape((5,10))
print_info(u)
print_info(v)

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
type:      <class 'numpy.ndarray'>
len:       50
dtype:     float64
shape:     (50,)
size:      50
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1
[[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
   1.2244898   1.42857143  1.63265306  1.83673469]
 [ 2.04081633  2.24489796  2.44897959  2.65306122  2.85714286  3.06122449
   3.

In [46]:
u = np.linspace(0, 10, 25) 
v = u.reshape((1,5,5))
print_info(u)
print_info(v)

[ 0.          0.41666667  0.83333333  1.25        1.66666667  2.08333333
  2.5         2.91666667  3.33333333  3.75        4.16666667  4.58333333
  5.          5.41666667  5.83333333  6.25        6.66666667  7.08333333
  7.5         7.91666667  8.33333333  8.75        9.16666667  9.58333333
 10.        ]
type:      <class 'numpy.ndarray'>
len:       25
dtype:     float64
shape:     (25,)
size:      25
ndim:      1
itemsize:  8
data:      <memory at 0x10624c408>
np.linalg.matrix_rank:  1
[[[ 0.          0.41666667  0.83333333  1.25        1.66666667]
  [ 2.08333333  2.5         2.91666667  3.33333333  3.75      ]
  [ 4.16666667  4.58333333  5.          5.41666667  5.83333333]
  [ 6.25        6.66666667  7.08333333  7.5         7.91666667]
  [ 8.33333333  8.75        9.16666667  9.58333333 10.        ]]]
type:      <class 'numpy.ndarray'>
len:       1
dtype:     float64
shape:     (1, 5, 5)
size:      25
ndim:      3
itemsize:  8
data:      <memory at 0x1058fb9a8>
np.linalg.matrix_rank: 

# Caution: Change shape using reshape method

In [47]:
a = np.linspace(1,12,6)
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [48]:
a.reshape(3,2)

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

In [49]:
a

array([ 1. ,  3.2,  5.4,  7.6,  9.8, 12. ])

In [50]:
try:
    a.reshape((3,2), inplace=True)
except Exception as e:
    print(e)

'inplace' is an invalid keyword argument for this function


reshape method는 오리지날을 건들이지 않고 reshape한 것을 리턴합니다.
inplace=True도 작동하지 않아요.
리턴한 것을 받아야만 모양을 바꿀 수 있어요.

In [51]:
a = a.reshape(3,2)
a

array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

# Change shape using flatten or ravel method

In [52]:
u = np.array([[1, 2], [3, 4], [5, 6]])
u

array([[1, 2],
       [3, 4],
       [5, 6]])

In [53]:
if 1:
    u.flatten()
else:
    u.ravel()

In [54]:
u

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
try:
    u.flatten(inplace=True)
except Exception as e:
    print(e)

'inplace' is an invalid keyword argument for this function


flatten method는 오리지날을 건들이지 않고 flatten한 것을 리턴합니다.
inplace=True도 작동하지 않아요.
리턴한 것을 받아야만 평평하게 펼 수 있어요.
reshape and ravel method도 같아요.

In [56]:
u = u.flatten()
u

array([1, 2, 3, 4, 5, 6])

In [57]:
u = np.array([[1, 2], [3, 4], [5, 6]])
u

array([[1, 2],
       [3, 4],
       [5, 6]])

In [58]:
u = u.reshape((6,))
u

array([1, 2, 3, 4, 5, 6])

In [59]:
u = np.array([[1, 2], [3, 4], [5, 6]])
u

array([[1, 2],
       [3, 4],
       [5, 6]])

In [60]:
u = u.ravel()
u

array([1, 2, 3, 4, 5, 6])

# Change shape using np.expand_dims, np.newaxis, or None

In [61]:
x0 = np.random.uniform(low=0.0, high=1.0, size=(3))
if 1:
    x1 = np.expand_dims(x0, axis=0)
    x2 = np.expand_dims(x0, axis=1)
elif 1:
    x1 = x0[np.newaxis, :]
    x2 = x0[:, np.newaxis]      
else:
    x1 = x0[None, :]
    x2 = x0[:, None] 

In [62]:
x0

array([0.02134083, 0.62015022, 0.75720606])

In [63]:
x1

array([[0.02134083, 0.62015022, 0.75720606]])

In [64]:
x2

array([[0.02134083],
       [0.62015022],
       [0.75720606]])

In [65]:
x0.shape

(3,)

In [66]:
x1.shape

(1, 3)

In [67]:
x2.shape

(3, 1)

# Simple aggregations

In [68]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [69]:
a.min()

1

In [70]:
a.max()

6

In [71]:
a.sum()

21

In [72]:
a.mean()

3.5

In [73]:
a.std()

1.707825127659933

In [74]:
a.var()

2.9166666666666665

In [75]:
try:
    a.sqrt()
except Exception as e:
    print(e)

'numpy.ndarray' object has no attribute 'sqrt'


In [76]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ],
       [2.23606798, 2.44948974]])

In [77]:
np.std(a)

1.707825127659933

In [78]:
a.sum(axis=0)

array([ 9, 12])

In [79]:
a.sum(axis=1)

array([ 3,  7, 11])

# Simple Math Operations

In [80]:
a = np.arange(4).reshape((2,2))
a

array([[0, 1],
       [2, 3]])

In [81]:
b = np.arange(1,5).reshape((2,2))
b

array([[1, 2],
       [3, 4]])

In [82]:
a+b

array([[1, 3],
       [5, 7]])

In [83]:
a-b

array([[-1, -1],
       [-1, -1]])

In [84]:
a*b

array([[ 0,  2],
       [ 6, 12]])

In [85]:
a/b

array([[0.        , 0.5       ],
       [0.66666667, 0.75      ]])

In [86]:
3*a

array([[0, 3],
       [6, 9]])

In [87]:
a/3

array([[0.        , 0.33333333],
       [0.66666667, 1.        ]])

In [88]:
a.dot(b)

array([[ 3,  4],
       [11, 16]])

In [89]:
b

array([[1, 2],
       [3, 4]])

In [90]:
b>0

array([[ True,  True],
       [ True,  True]])