# Componentwise Operations

# Componentwise Operations (with broadcasting)

<div align="center"><img src="img/broadcasting_example_1.png" width="40%"></div>

https://www.python-course.eu/images/broadcasting_example_1.png

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 1], [2, 3]])
a

array([[1, 1],
       [2, 3]])

In [3]:
b = np.array([[1, 2], [1, 3]])
b

array([[1, 2],
       [1, 3]])

In [4]:
a+2

array([[3, 3],
       [4, 5]])

In [5]:
a-2

array([[-1, -1],
       [ 0,  1]])

In [6]:
a*2

array([[2, 2],
       [4, 6]])

In [7]:
a/2

array([[0.5, 0.5],
       [1. , 1.5]])

In [8]:
a+b

array([[2, 3],
       [3, 6]])

In [9]:
a-b

array([[ 0, -1],
       [ 1,  0]])

In [10]:
a*b

array([[1, 2],
       [2, 9]])

In [11]:
a/b

array([[1. , 0.5],
       [2. , 1. ]])

In [12]:
a%2

array([[1, 1],
       [0, 1]])

In [13]:
a//2

array([[0, 0],
       [1, 1]])

In [14]:
a**2

array([[1, 1],
       [4, 9]])

In [15]:
np.power(a, 2)

array([[1, 1],
       [4, 9]])

In [16]:
2**a

array([[2, 2],
       [4, 8]])

In [17]:
np.power(2, a)

array([[2, 2],
       [4, 8]])

In [18]:
np.exp(a)

array([[ 2.71828183,  2.71828183],
       [ 7.3890561 , 20.08553692]])

In [19]:
np.exp2(a)

array([[2., 2.],
       [4., 8.]])

In [20]:
print(np.log(a))
print()
print(np.log2(a))
print()
print(np.log10(a))

[[0.         0.        ]
 [0.69314718 1.09861229]]

[[0.        0.       ]
 [1.        1.5849625]]

[[0.         0.        ]
 [0.30103    0.47712125]]


In [21]:
print(np.sin(a))
print()
print(np.cos(a))
print()
print(np.tan(a))

[[0.84147098 0.84147098]
 [0.90929743 0.14112001]]

[[ 0.54030231  0.54030231]
 [-0.41614684 -0.9899925 ]]

[[ 1.55740772  1.55740772]
 [-2.18503986 -0.14254654]]


In [22]:
a

array([[1, 1],
       [2, 3]])

In [23]:
print(np.arcsin(a))
print()
print(np.arccos(a))
print()
print(np.arctan(a))

[[1.57079633 1.57079633]
 [       nan        nan]]

[[ 0.  0.]
 [nan nan]]

[[0.78539816 0.78539816]
 [1.10714872 1.24904577]]


/Users/sungchul/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: invalid value encountered in arcsin
  if __name__ == '__main__':
/Users/sungchul/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:3: RuntimeWarning: invalid value encountered in arccos
  app.launch_new_instance()


In [24]:
print(np.ceil(a))
print()
print(np.floor(a))
print()
print(np.round(a))

[[1. 1.]
 [2. 3.]]

[[1. 1.]
 [2. 3.]]

[[1 1]
 [2 3]]


# out keyword

For large calculations, it is sometimes useful to be able to specify the array where the result of the calculation will be stored. Rather than creating a temporary array, this can be used to write computation results directly to the memory location where you'd like them to be. For all ufuncs, this can be done using the out argument of the function:

Python Data Science Handbook by Jake Vanderplas [github](https://github.com/jakevdp/PythonDataScienceHandbook) 

In [25]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [26]:
x = np.arange(5)
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
