# Other Operations

In [1]:
import pandas as pd
import numpy as np

# np.where

In [2]:
u = np.array([0,1,2,3,3,3,0,1,2,3])
u

array([0, 1, 2, 3, 3, 3, 0, 1, 2, 3])

In [3]:
v = np.where(u > 2, 2, -2) # args: condition, value if True, value if False
v

array([-2, -2, -2,  2,  2,  2, -2, -2, -2,  2])

In [4]:
v = np.where(u > 2, 2,  u) # any of the 3 arguments can be an array
v

array([0, 1, 2, 2, 2, 2, 0, 1, 2, 2])

# np.unique

In [5]:
u = np.array([0,1,2,3,3,3,0,1,2,3])
u

array([0, 1, 2, 3, 3, 3, 0, 1, 2, 3])

In [6]:
v = np.unique(u)
v

array([0, 1, 2, 3])

# np.isnan

In [7]:
df = pd.read_excel('./data/sample.xlsx')
df = np.array(df)
print("Original df")
print(df)

Original df
[[93. 84. 73. 68.]
 [97. 67. 57. nan]
 [87. 87. nan 77.]
 [68. 87. 46. 87.]
 [67. 48. 48. 76.]]


In [8]:
bool_nan = np.isnan(df)
df[bool_nan] = -7000
print("df with replacing nan with -7000")
print(df)

df with replacing nan with -7000
[[   93.    84.    73.    68.]
 [   97.    67.    57. -7000.]
 [   87.    87. -7000.    77.]
 [   68.    87.    46.    87.]
 [   67.    48.    48.    76.]]
