# Iterate numpy array using nditer

[numpy tutorial: iterate numpy array using nditer by codebasics](https://www.youtube.com/watch?v=XawR6CjAYV4)

In [1]:
import numpy as np

In [2]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Iteration not using np.nditer

각각의 로가 프린트되도록 해보죠.

In [3]:
for row in a:
    print(row)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


각각의 아이템이 프린트되도록 해보죠.

In [4]:
for row in a:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


a.flat, a.flatten(), a.ravel()을 쓰면 같은 작업을 하나의 for loop로 처리할 수 있다.  

In [5]:
for i in a.flat:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [6]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [7]:
for i in a.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


a.flat, a.flatten(), a.ravel() 각각을 프린트해 보자.

In [8]:
a.flat

a.flat는 numpy.flatiter object이다. 
flatiter is just the type of the iterator object returned by flat ([docs](https://docs.scipy.org/doc/numpy/reference/generated/numpy.flatiter.html)). So all you need to know about it is that it's an iterator like any other.

https://stackoverflow.com/questions/30523123/when-to-use-flat-flatiter-or-flatten

In [9]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

Obviously, flatten or ravel consumes more memory and cpu, as it creates a new array, while flat only creates the iterator object, which is super fast.

https://stackoverflow.com/questions/30523123/when-to-use-flat-flatiter-or-flatten

> You just need to iterate - a.flat

> You need actual np.ndarray - a.flatten(), a.ravel()  

# Iteration using np.nditer

class numpy.nditer

Efficient multi-dimensional iterator object to iterate over arrays. To get started using this object, see the [introductory guide to array iteration](https://docs.scipy.org/doc/numpy-1.14.0/reference/arrays.nditer.html#arrays-nditer).

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nditer.html

**order** : {‘C’, ‘F’, ‘A’, ‘K’}, optional

Controls the iteration order. ‘C’ means C order, ‘F’ means Fortran order, ‘A’ means ‘F’ order if all the arrays are Fortran contiguous, ‘C’ order otherwise, and ‘K’ means as close to the order the array elements appear in memory as possible. This also affects the element memory order of “allocate” operands, as they are allocated to be compatible with iteration order. Default is ‘K’.

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nditer.html

In [11]:
# https://www.tutorialspoint.com/numpy/numpy_iterating_over_array.htm

a = np.arange(0,60,5).reshape(3,4)

print('Original array is:')
print(a) 
print()   
   
print('Modified array is:') 
for x in np.nditer(a): 
    print(x, end=', ')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Modified array is:
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

The default order 'K' of iteration is chosen to match the memory layout of an array, without considering a particular ordering. This can be seen by iterating over the transpose of the above array.

https://www.tutorialspoint.com/numpy/numpy_iterating_over_array.htm

In [12]:
# https://www.tutorialspoint.com/numpy/numpy_iterating_over_array.htm

a = np.arange(0,60,5).reshape(3,4) 
   
print('Original array is:')
print(a) 
print()  
   
print('Transpose of the original array is:' )
b = a.T 
print(b) 
print()  
   
print('Modified array is:') 
for x in np.nditer(b): 
    print(x, end=', ')

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]

Modified array is:
0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [13]:
# C style ordering

a = np.arange(0,60,5).reshape(3,4)
print(a)
print()

for x in np.nditer(a, order='C'):
    print(x, end=', ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 

In [14]:
# Fortan style ordering

a = np.arange(0,60,5).reshape(3,4)
print(a)
print()

for x in np.nditer(a, order='F'):
    print(x, end=', ')

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]

0, 20, 40, 5, 25, 45, 10, 30, 50, 15, 35, 55, 

```
“external_loop” causes the values given to be one-dimensional arrays with multiple values instead of zero-dimensional arrays.
```

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nditer.html

In [15]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
for x in np.nditer(a, flags=['external_loop'], order='C'):
    print(x)
    print(type(x))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
<class 'numpy.ndarray'>


In [17]:
a = a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
a = np.arange(12).reshape(3,4)
a = a.ravel()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [20]:
for x in np.nditer(a, flags=['external_loop'], order='F'):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [21]:
a = np.arange(12).reshape(3,4)
for x in a:
    print(x)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


꺽쇠를 하나 뿌려트려서 1D array를 생성시키는군요.

```
“readwrite” indicates the operand will be read from and written to
```

https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.nditer.html

In [22]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [23]:
for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = x * x

In [24]:
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [25]:
a = np.arange(12).reshape(3,4)**2
a

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

# Iteration using np.nditer with two broadcastable arrays concurrently

In [26]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
b = np.arange(3, 15, 4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [28]:
for x, y in np.nditer([a,b]):
    print (x,y)

0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


np.nditer is, more than anything, a stepping stone for developing cython or other c-api code. The c-api version of nditer has a lot of power, and relatively good speed. The python equivalent is not fast nor powerful.

https://stackoverflow.com/questions/48724449/iterate-over-two-numpy-2d-matrices-using-nditer