# Vector Addition and Scalar Multiplication

In [1]:
import numpy as np

# Vector Addition 

<div align="center"><img src="img/Vector_addition.png" width="40%"></div>

https://upload.wikimedia.org/wikipedia/commons/e/ef/Vector_addition.png

In [2]:
def generate_u_and_v(choice_of_u_and_v):
    
    if choice_of_u_and_v == 0:   # scalar, scalar
        u = np.pi
        v = np.exp(1)
    elif choice_of_u_and_v == 1: # scalar, vector
        u = np.arange(1, 6)
        v = 3
    elif choice_of_u_and_v == 2: # vector, scalar
        u = 3
        v = np.arange(1, 6)
    elif choice_of_u_and_v == 3: # scalar, matrix
        u = 3
        v = np.random.rand(2, 2)
    elif choice_of_u_and_v == 4: # matrix, scalar
        u = np.random.rand(2, 2)
        v = 3
    elif choice_of_u_and_v == 5: # vector, vector
        u = np.arange(0, 5)
        v = np.arange(1, 6)
    elif choice_of_u_and_v == 6: # vector, matrix
        u = np.random.rand(2)
        v = np.random.rand(2, 2)
    elif choice_of_u_and_v == 7: # matrix, vector
        u = np.random.rand(2, 2)
        v = np.random.rand(2)
    else:                        # matrix, matrix
        u = np.random.rand(2, 2)
        v = np.random.rand(2, 2)

    return u, v

In [3]:
def print_info(u):
    print(u)
    print("Type :        ", type(u))
    try:
        print("Length :      ", len(u))
        print("Shape :       ", u.shape)
        print("Data Type :   ", u.dtype)
        print("Size :        ", u.size)
        print("Rank :        ", u.ndim)
        print("Matrix Rank : ", np.linalg.matrix_rank(u))
    except:
        pass

In [4]:
def print_info_on_u_v_w(u,v,w):
    print('Info on u')
    print_info(u)
    print()
    print('Info on v')
    print_info(v)
    print()
    print('Info on w')
    print_info(w)

위에서 정의한 함수 generate_u_and_v를 이용,
더하고자 하는 두 벡터 u, v를 생성하자.
choice_of_u_and_v를 0, 1, 2,..., 8중 하나의 정수를 선택하여 지정한다.
이를 generate_u_and_v에 집어넣고 실행시키면,
더하고자 하는 두 벡터 u, v를 생성하여준다.

In [5]:
choice_of_u_and_v = 3
u, v = generate_u_and_v(choice_of_u_and_v)

두 벡터 u, v를 더하여 w라고 하자.

In [6]:
w = u + v

u, v, w의 관련 정보를 프린트하자.

In [7]:
print_info_on_u_v_w()

Info on u
3
Type :         <class 'int'>

Info on v
[[0.08296011 0.55231508]
 [0.34852507 0.25102319]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on w
[[3.08296011 3.55231508]
 [3.34852507 3.25102319]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


# Scalar Multiplication

<div align="center"><img src="img/1.3.5-scalar-multiplication.png" width="40%"></div>

http://ibguides.com/physics/notes/vectors-and-scalars

위에서 정의한 함수 generate_u_and_v를 이용,
스칼라 멀티플리케이션하고자하는 스칼라 혹은 벡터 u, v를 생성하자.
choice_of_u_and_v를 0, 1, 2,..., 3중 하나의 정수를 선택하여 지정한다.
이를 generate_u_and_v에 집어넣고 실행시키면,
스칼라 멀티플리케이션하고자하는 스칼라 혹은 벡터 u, v를 생성하여준다.

In [8]:
choice_of_u_and_v = 3
u, v = generate_u_and_v(choice_of_u_and_v)

u, v를 스칼라 멀티플리케이션하여 w라고 하자.

In [9]:
w = u * v

u, v, w의 관련 정보를 프린트하자.

In [10]:
print_info_on_u_v_w()

Info on u
3
Type :         <class 'int'>

Info on v
[[0.51101813 0.00118405]
 [0.73507789 0.50839535]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on w
[[1.5330544  0.00355216]
 [2.20523366 1.52518605]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2
