# Matrix Multiplication and Component-wise Multiplication

In [1]:
import numpy as np

# Matrix Multiplication

> np.dot

> dot method

> @

In [2]:
def print_info(u):
    print(u)
    print("Type :        ", type(u))
    try:
        print("Length :      ", len(u))
        print("Shape :       ", u.shape)
        print("Data Type :   ", u.dtype)
        print("Size :        ", u.size)
        print("Rank :        ", u.ndim)
        print("Matrix Rank : ", np.linalg.matrix_rank(u))
    except:
        pass

In [3]:
def print_info_on_u_v_w(u,v,w):
    print('Info on u')
    print_info(u)
    print()
    print('Info on v')
    print_info(v)
    print()
    print('Info on w')
    print_info(w)

In [4]:
u = np.random.rand(2, 2)
v = np.random.rand(2, 2)

In [5]:
w1 = np.dot(u, v)
w2 = u.dot(v)
w3 = u @ v

In [6]:
print_info_on_u_v_w(u,v,w1)

Info on u
[[0.86600603 0.08024274]
 [0.40460752 0.05808239]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on v
[[0.84550584 0.93613457]
 [0.69244262 0.53359852]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on w
[[0.78777664 0.85351559]
 [0.38231674 0.40975977]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


In [7]:
print_info(w2)

[[0.78777664 0.85351559]
 [0.38231674 0.40975977]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


In [8]:
print_info(w3)

[[0.78777664 0.85351559]
 [0.38231674 0.40975977]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


# Component-wise Multiplication

> *

In [9]:
w4 = u * v

In [10]:
print_info_on_u_v_w(u,v,w4)

Info on u
[[0.86600603 0.08024274]
 [0.40460752 0.05808239]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on v
[[0.84550584 0.93613457]
 [0.69244262 0.53359852]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2

Info on w
[[0.73221315 0.07511801]
 [0.28016749 0.03099268]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2
