In [1]:
import numpy as np

In [2]:
np.random.seed(337)

In [3]:
def print_info(u):
    print(u)
    print("Type :        ", type(u))
    try:
        print("Length :      ", len(u))
        print("Shape :       ", u.shape)
        print("Data Type :   ", u.dtype)
        print("Size :        ", u.size)
        print("Rank :        ", u.ndim)
        print("Matrix Rank : ", np.linalg.matrix_rank(u))
    except:
        pass

In [4]:
def print_info_on_u_v_w(u,v,w):
    print('Info on u')
    print_info(u)
    print()
    print('Info on v')
    print_info(v)
    print()
    print('Info on w')
    print_info(w)

# Determinant

```
numpy.linalg.det(a)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.det.html

In [5]:
u = np.random.rand(2, 2)
u

array([[0.79990679, 0.15356741],
       [0.5677806 , 0.04969421]])

In [6]:
np.linalg.det(u)

-0.04744186416770812

# Condition Number

```
numpy.linalg.cond(x, p=None)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.cond.html

In [7]:
u = np.random.rand(2, 2)
u

array([[0.54533612, 0.23003453],
       [0.33956951, 0.38841324]])

In [8]:
np.linalg.cond(u)

4.382639088260375

# Matrix Inverse

> np.linalg.inv

> np.linalg.pinv

```
numpy.linalg.inv(a)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

```
numpy.linalg.pinv(a, rcond=1e-15)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.pinv.html

In [9]:
u = np.random.rand(2, 2)
u

array([[0.16388442, 0.74331859],
       [0.87979309, 0.25292547]])

In [10]:
v1 = np.linalg.inv(u)
v1

array([[-0.41292875,  1.21354965],
       [ 1.43635932, -0.26755941]])

In [11]:
print(u@v1)
print(v1@u)

[[ 1.00000000e+00 -1.51322172e-17]
 [ 1.58819390e-17  1.00000000e+00]]
[[ 1.00000000e+00 -2.89666724e-17]
 [ 4.08668994e-17  1.00000000e+00]]


In [12]:
v2 = np.linalg.pinv(u)
v2

array([[-0.41292875,  1.21354965],
       [ 1.43635932, -0.26755941]])

In [13]:
print(u@v2)
print(v2@u)

[[ 1.00000000e+00  2.05428818e-16]
 [-2.63622575e-16  1.00000000e+00]]
[[ 1.00000000e+00 -8.38282378e-17]
 [ 1.25197905e-16  1.00000000e+00]]


# Transpose

> np.transpose

> .T

```
numpy.transpose(a, axes=None)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html

In [14]:
u = np.random.rand(2, 2)
u

array([[0.15831741, 0.37167054],
       [0.70927357, 0.78333967]])

In [15]:
v1 = np.transpose(u)
v2 = u.T

In [16]:
print_info(u)

[[0.15831741 0.37167054]
 [0.70927357 0.78333967]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


In [17]:
print_info(v1)

[[0.15831741 0.70927357]
 [0.37167054 0.78333967]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


In [18]:
print_info(v2)

[[0.15831741 0.70927357]
 [0.37167054 0.78333967]]
Type :         <class 'numpy.ndarray'>
Length :       2
Shape :        (2, 2)
Data Type :    float64
Size :         4
Rank :         2
Matrix Rank :  2


# Trace

> np.trace

```
numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)[source]
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.trace.html

In [19]:
u = np.random.rand(2, 2)
u

array([[0.39652564, 0.80421867],
       [0.17752749, 0.454777  ]])

In [20]:
np.trace(u)

0.8513026313766898

# Inner Product

$$
{\bf u} \cdot {\bf v} = \sum_{i=1}^d u_iv_i
$$

In [21]:
u = np.array([1,2,3])
v = np.array([3,4,0])

In [22]:
w = np.dot(u,v)
print_info_on_u_v_w(u,v,w)

Info on u
[1 2 3]
Type :         <class 'numpy.ndarray'>
Length :       3
Shape :        (3,)
Data Type :    int64
Size :         3
Rank :         1
Matrix Rank :  1

Info on v
[3 4 0]
Type :         <class 'numpy.ndarray'>
Length :       3
Shape :        (3,)
Data Type :    int64
Size :         3
Rank :         1
Matrix Rank :  1

Info on w
11
Type :         <class 'numpy.int64'>


# Cross Product (only in ${\bf R}^3$)

$$
{\bf u} \times {\bf v} = \left|
\begin{array}{lll}
{\bf i}&{\bf j}&{\bf k}\\
u_1&u_2&u_3\\
v_1&v_2&v_3\\
\end{array}\right|
$$

```
numpy.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None)
```

https://docs.scipy.org/doc/numpy/reference/generated/numpy.cross.html

In [23]:
u = np.array([1,2,3])
v = np.array([3,4,0])

In [24]:
w = np.cross(u,v)
print_info_on_u_v_w(u,v,w)

Info on u
[1 2 3]
Type :         <class 'numpy.ndarray'>
Length :       3
Shape :        (3,)
Data Type :    int64
Size :         3
Rank :         1
Matrix Rank :  1

Info on v
[3 4 0]
Type :         <class 'numpy.ndarray'>
Length :       3
Shape :        (3,)
Data Type :    int64
Size :         3
Rank :         1
Matrix Rank :  1

Info on w
[-12   9  -2]
Type :         <class 'numpy.ndarray'>
Length :       3
Shape :        (3,)
Data Type :    int64
Size :         3
Rank :         1
Matrix Rank :  1
