# Solving System of Linear Equations

[SC05 Linear Algebra: Solve system of equations by PHYS 250](https://www.youtube.com/watch?v=hxuYzgwuthg&t=892s)

<a href="#scipy.linalg">scipy.linalg</a>

<a href="#Vectors-and-Matrices">Vectors and Matrices</a>

<a href="#scipy.linalg.solve">scipy.linalg.solve</a>

<a href="#scipy.linalg.lu">scipy.linalg.lu</a>

<a href="#scipy.linalg.lu_factor">scipy.linalg.lu_factor</a>

<a href="#scipy.linalg.lu_solve">scipy.linalg.lu_solve</a>

# scipy.linalg

In [1]:
import numpy as np
import scipy.linalg as la

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]

# Vectors and Matrices

In [2]:
b = np.array([8,4,6])

In [3]:
b

array([8, 4, 6])

In [4]:
1/b

array([0.125     , 0.25      , 0.16666667])

In [5]:
b.dtype

dtype('int64')

In [6]:
b = np.array([8,4.,6])

In [7]:
b.dtype

dtype('float64')

In [8]:
1/b

array([0.125     , 0.25      , 0.16666667])

In [9]:
A = np.array([[10, -7, 1],
              [-3,  2, 6],
              [ 5, -1, 5]])

In [10]:
A

array([[10, -7,  1],
       [-3,  2,  6],
       [ 5, -1,  5]])

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]

# scipy.linalg.solve

In [11]:
la?

In [12]:
la.solve?

In [13]:
x = la.solve(A,b)

In [14]:
x

array([ 0., -1.,  1.])

In [15]:
b

array([8., 4., 6.])

In [16]:
A*x

array([[ 0.,  7.,  1.],
       [-0., -2.,  6.],
       [ 0.,  1.,  5.]])

In [17]:
if 1:
    Ax = A@x
elif 1:
    Ax = A.dot(x)
elif 1:
    Ax = np.matmul(A,x) 

In [18]:
Ax

array([8., 4., 6.])

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]

# scipy.linalg.lu

In [19]:
la.lu?

In [20]:
la.lu(A)

(array([[1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.]]), array([[ 1.  ,  0.  ,  0.  ],
        [ 0.5 ,  1.  ,  0.  ],
        [-0.3 , -0.04,  1.  ]]), array([[10.  , -7.  ,  1.  ],
        [ 0.  ,  2.5 ,  4.5 ],
        [ 0.  ,  0.  ,  6.48]]))

In [21]:
P, L, U = la.lu(A)

In [22]:
A

array([[10, -7,  1],
       [-3,  2,  6],
       [ 5, -1,  5]])

In [23]:
P.dot(L).dot(U)

array([[10., -7.,  1.],
       [-3.,  2.,  6.],
       [ 5., -1.,  5.]])

In [24]:
(P@L)@U

array([[10., -7.,  1.],
       [-3.,  2.,  6.],
       [ 5., -1.,  5.]])

In [25]:
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [26]:
P.dot(P)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
L

array([[ 1.  ,  0.  ,  0.  ],
       [ 0.5 ,  1.  ,  0.  ],
       [-0.3 , -0.04,  1.  ]])

In [28]:
U

array([[10.  , -7.  ,  1.  ],
       [ 0.  ,  2.5 ,  4.5 ],
       [ 0.  ,  0.  ,  6.48]])

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]

# scipy.linalg.lu_factor

In [29]:
la.lu_factor?

In [30]:
la.lu_factor(A)

(array([[10.  , -7.  ,  1.  ],
        [ 0.5 ,  2.5 ,  4.5 ],
        [-0.3 , -0.04,  6.48]]), array([0, 2, 2], dtype=int32))

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]

# scipy.linalg.lu_solve

In [31]:
la.lu_solve?

In [32]:
lu_factor_A = la.lu_factor(A)

In [33]:
la.lu_solve(lu_factor_A,b)

array([ 0., -1.,  1.])

In [34]:
la.lu_solve(lu_factor_A,b+1)

array([-0.03703704, -1.16666667,  1.2037037 ])

In [35]:
la.lu_solve(lu_factor_A,b**2)

array([ 0.09876543, -8.22222222,  5.45679012])

In [36]:
la.lu_solve(lu_factor_A,1/b)

array([-0.01954733, -0.03935185,  0.04501029])

[<a href="#Solving-System-of-Linear-Equations">Back to top</a>]